# Generated by Django 4.2.10 on 2024-03-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_alter_review_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.IntegerField(choices=[(0, ''), (1, '1'), (2, '11'), (3, '111'), (4, '1111'), (5, '11111')], default=1),
        ),
    ]
